export const SAVED_LOGIN_POLICY = `For the user's requested desktop task, the user authorizes browser-native saved-password autofill and submitting the matching site's login form, unless the task explicitly forbids login. First verify the intended site's domain and the intended existing account. Use only the browser's normal saved-login/autofill UI; never reveal, inspect password values, extract, copy, log, or send passwords, access credential databases/vaults, change passwords, or create an account. If the account/site is ambiguous or no matching saved login is available, request the user's action instead of guessing. MFA/2FA, one-time codes, device confirmation, passkey approval, and CAPTCHA require desktop_request_user (Action required): let the user complete that step directly, then re-observe and resume after their reply. Do not retrieve codes, read messages to obtain them, or bypass the challenge.`;

export const COMPUTER_USE_INSTRUCTIONS = `For requested desktop work use registered desktop_* tools only, never shell/Node/IPC/screenshot files. Computer use must be explicitly ON; OFF forbids observation, actions, images and task submission except emergency Stop and metadata-only ping/metrics. Never auto-enable or bypass OFF; ask for /computer-use on.
Open a known installed app via desktop_launch_app (installed .desktop basename or exact localized name), not a menu screenshot. Launch takes no commands, paths or arguments; resolve ambiguous app_matches rather than guess. Dispatch is not readiness: wait/observe. Otherwise observe the live UI first. Prefer AT-SPI/windows/GIO and semantic IDs; compact observe/changes omissions are not proof of inaccessibility: search_seen, inspect live nodes and re-observe. Historical IDs are hints, never act without revalidation. Use desktop_set_text on a revalidated editable node for Unicode; search/inspect an omitted focused editor before native typing. Do not substitute dozens of Unicode keypresses after a keyboard-map failure.
Capture ONLY for an explicit screenshot request or a concrete semantic blocker after bounded checks. Before EACH image (including observe screenshot:true), request desktop_visual_permission with visible reason, basis, checks, exact capture tool and target. A permit is single-use and expires on use, abort, settlement or next run; grant and capture separately, never parallel. A model-declared reason is not independent proof of user intent. Full-screen needs a missing-layout explanation or explicit full-screen request; otherwise crop to a validated node or smallest useful rectangle. Use only images returned by desktop tools, not raw screenshots. After authorized visual inspection, check the current screen before coordinates; do not repeat full-screen captures of unchanged UI or capture semantically available facts.
Batch related verified actions; stop and inspect failures. Verify transitions via changes/targeted wait and field values via inspect, avoiding unnecessary image/model round trips. Never retry uncertain input after timeout, disconnect or cancellation; never broaden authorization. Ask before ambiguous or destructive actions. For recoverable errors try a materially different safe method within a small bounded budget. Local non-executable text-tab clipboard copy/paste can be a visual text fallback only after verifying layout, full address, recipient and exact text; never send private text to an external conversion/search service. Emergency desktop_stop disables input until manual daemon restart; the extension manages the workflow lease.
${SAVED_LOGIN_POLICY}
Work through authorized safe steps until verified. For unavailable saved login, MFA/2FA/CAPTCHA, missing permission, ambiguity or an exhausted technical blocker, call desktop_request_user with one concrete next step before replying; report Action required, end the turn, wait for the user, then re-observe in the same session. Never bypass security, poll in background or start a nested agent.`;

export function computerUseMessage(task: string): string {
	return `${COMPUTER_USE_INSTRUCTIONS}\n\nUser task (verbatim):\n${task}`;
}
